trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - bash: echo "Do the Build"
      - bash: hostname
      - bash: echo $(Agent.OS)
      - bash: echo $(Agent.WorkFolder)
      - bash: java --version
      - bash: mvn --version
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.StagingDirectory)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: echo $(System.HostType)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
            **/*.yaml
            **/*.tf
          TargetFolder: '$(Build.StagingDirectory)'
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - bash:  echo "Test the pipe line"
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - bash: echo "Build has been Publish "
  
  - Stage: DEV
    jobs:
    - job: DEV-BuildJob
      steps:
      - bash: "this is Dev build job"
      
