# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/test/iam'
    backendServiceAWS: 'test'
    backendAWSBucketName: 'tarlok-s3-tes111'
    backendAWSKey: 'kubernetes-dev.tf'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'destroy' # this is testest
    workingDirectory: '$(System.DefaultWorkingDirectory)/test/iam'
    environmentServiceNameAWS: 'test'
