trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/test/iam'
    backendServiceAWS: 'test'
    backendAWSBucketName: 'tarlok-s3-tes111'
    backendAWSKey: 'kubernetes-dev.tf'


- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/test/iam'
    environmentServiceNameAWS: 'test'